# Generated by Django 3.0.3 on 2020-03-02 18:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentletter',
            name='template',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
