# Generated by Django 3.0.3 on 2020-03-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentsubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentletter',
            name='template',
            field=models.TextField(),
        ),
    ]
